wandb: Currently logged in as: hadars (autoconvnext). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.13.5 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.4
wandb: Run data is saved locally in /home/s3092593/benchmarking_rl/wandb/run-20221201_074714-2nb0cs49
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run valiant-water-1
wandb: ⭐️ View project at https://wandb.ai/autoconvnext/benchmark_final_impala_large_2_DQN_modern_Phoenix_model_37250000_0_impala_large_2
wandb: 🚀 View run at https://wandb.ai/autoconvnext/benchmark_final_impala_large_2_DQN_modern_Phoenix_model_37250000_0_impala_large_2/runs/2nb0cs49
wandb: Waiting for W&B process to finish... (success).
wandb: 
wandb: Run history:
wandb: loss █▇▇▆▅▄▄▄▄▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▁▁▁▁▁▂
wandb:  mae █▇▆▄▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▂▂▂▂▃▃▄▄▄▄
wandb: 
wandb: Run summary:
wandb: loss 0.18875
wandb:  mae 1.0363
wandb: 
wandb: Synced valiant-water-1: https://wandb.ai/autoconvnext/benchmark_final_impala_large_2_DQN_modern_Phoenix_model_37250000_0_impala_large_2/runs/2nb0cs49
wandb: Synced 6 W&B file(s), 0 media file(s), 1 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20221201_074714-2nb0cs49/logs
wandb: wandb version 0.13.5 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.4
wandb: Run data is saved locally in /home/s3092593/benchmarking_rl/wandb/run-20221201_085746-2vq4tekv
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run avid-cherry-2
wandb: ⭐️ View project at https://wandb.ai/autoconvnext/benchmark_final_impala_large_2_DQN_modern_Phoenix_model_37250000_0_impala_large_2
wandb: 🚀 View run at https://wandb.ai/autoconvnext/benchmark_final_impala_large_2_DQN_modern_Phoenix_model_37250000_0_impala_large_2/runs/2vq4tekv
wandb: Waiting for W&B process to finish... (success).
wandb: 
wandb: Run history:
wandb: loss █▆▆▅▅▄▄▄▄▃▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▁▁
wandb:  mae █▆▅▄▃▂▂▂▂▂▂▁▁▁▁▁▁▁▁▂▂▁▂▂▂▂▂▂▃▃
wandb: 
wandb: Run summary:
wandb: loss 0.16497
wandb:  mae 1.01512
wandb: 
wandb: Synced avid-cherry-2: https://wandb.ai/autoconvnext/benchmark_final_impala_large_2_DQN_modern_Phoenix_model_37250000_0_impala_large_2/runs/2vq4tekv
wandb: Synced 6 W&B file(s), 0 media file(s), 1 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20221201_085746-2vq4tekv/logs
wandb: wandb version 0.13.5 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.4
wandb: Run data is saved locally in /home/s3092593/benchmarking_rl/wandb/run-20221201_100912-qwzmk4vi
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run efficient-shape-3
wandb: ⭐️ View project at https://wandb.ai/autoconvnext/benchmark_final_impala_large_2_DQN_modern_Phoenix_model_37250000_0_impala_large_2
wandb: 🚀 View run at https://wandb.ai/autoconvnext/benchmark_final_impala_large_2_DQN_modern_Phoenix_model_37250000_0_impala_large_2/runs/qwzmk4vi
wandb: Waiting for W&B process to finish... (success).
wandb: 
wandb: Run history:
wandb: loss █▅▅▅▄▄▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁
wandb:  mae █▅▄▃▃▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▁▂▁
wandb: 
wandb: Run summary:
wandb: loss 0.16718
wandb:  mae 0.96973
wandb: 
wandb: Synced efficient-shape-3: https://wandb.ai/autoconvnext/benchmark_final_impala_large_2_DQN_modern_Phoenix_model_37250000_0_impala_large_2/runs/qwzmk4vi
wandb: Synced 6 W&B file(s), 0 media file(s), 1 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20221201_100912-qwzmk4vi/logs
wandb: wandb version 0.13.5 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.4
wandb: Run data is saved locally in /home/s3092593/benchmarking_rl/wandb/run-20221201_112035-27p7nlho
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run jumping-flower-4
wandb: ⭐️ View project at https://wandb.ai/autoconvnext/benchmark_final_impala_large_2_DQN_modern_Phoenix_model_37250000_0_impala_large_2
wandb: 🚀 View run at https://wandb.ai/autoconvnext/benchmark_final_impala_large_2_DQN_modern_Phoenix_model_37250000_0_impala_large_2/runs/27p7nlho
--- Logging error ---
Traceback (most recent call last):
  File "/data1/s3092593/rlenv/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/data1/s3092593/rlenv/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
OSError: [Errno 122] Disk quota exceeded
Call stack:
  File "/data1/s3092593/rlenv/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/data1/s3092593/rlenv/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 50, in run
    self._run()
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 101, in _run
    self._process(record)
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 308, in _process
    self._sm.send(record)
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 303, in send
    logger.debug(f"send: {record_type}")
Message: 'send: stats'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/data1/s3092593/rlenv/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/data1/s3092593/rlenv/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
OSError: [Errno 122] Disk quota exceeded
Call stack:
  File "/data1/s3092593/rlenv/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/data1/s3092593/rlenv/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 50, in run
    self._run()
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 101, in _run
    self._process(record)
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 263, in _process
    self._hm.handle(record)
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/handler.py", line 130, in handle
    handler(record)
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/handler.py", line 138, in handle_request
    logger.debug(f"handle_request: {request_type}")
Message: 'handle_request: stop_status'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/data1/s3092593/rlenv/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/data1/s3092593/rlenv/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
OSError: [Errno 122] Disk quota exceeded
Call stack:
  File "/data1/s3092593/rlenv/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/data1/s3092593/rlenv/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 50, in run
    self._run()
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 101, in _run
    self._process(record)
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 263, in _process
    self._hm.handle(record)
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/handler.py", line 130, in handle
    handler(record)
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk